### ISSUE TITLE
The predicate does not have a VP table

### ISSUE THREAD

**Issue by arrascue** [tf-dbis-uni-freiburg/PRoST#13]
Dataset: movielens100k
Query: {(?s) (http://example.org/movielens#rates) (?o) } 
Error: 
The predicate does not have a VP table: http://example.org/movielens#rates
Exception in thread "main" java.lang.NullPointerException
        at JoinTree.JoinTree.computeJoins(JoinTree.java:71)

However, Hive contains the VP for that property: /user/hive/warehouse/movielens100k.db/vp_http___example_org_movielens_rates

This bug might be related to Matteo's bug: https://github.com/tf-dbis-uni-freiburg/PRoST/issues/9

**Comment by matteuan** [comment]
Have you provided a working stats file? If the stats file is empty (for some other reasons) the translator won't find the table. The stats file is also used to get the proper names of the tables.

**Comment by arrascue** [comment]
Yes, you are right. I was just about to remove this issue because indeed the .stats file is empty. Therefore, this issue is the same as: https://github.com/tf-dbis-uni-freiburg/PRoST/issues/15
