### ISSUE TITLE
Condition to check if a query contains a filter seems not to be working correctly

### ISSUE THREAD

**Issue by arrascue** [tf-dbis-uni-freiburg/PRoST#19]
To reproduce it is enough to evaluate a simple query like:
_select ?s ?o where {?s <some_prop_as_constant> ?o}_

Although the query does not contain any filter, the condition in JoinTree.JoinTree, line 71:
_results = **this.root.filter == null** ? results.select(selectedColumns)
		: results.filter(this.root.filter).select(selectedColumns);_
returns false, but I guess it should return true, right?
Otherwise, it goes for the  _results.filter(this.root.filter)_ branch, thus evaluating on an empty filter(?)

**Comment by polinankoleva** [comment]
The bug cannot be reproduced.
