### ISSUE TITLE
generateTT always true

### ISSUE THREAD

**Issue by polinankoleva** [tf-dbis-uni-freiburg/PRoST#24]
Is there a case when TT won't be generated? In the code, the variable stays always true, but at the same time multiple if/else statements are introduced checking it.

**Comment by arrascue** [comment]
The TT is at the moment always generated, because other partitioning strategies have a dependency on the TT.  So even if the TT is not explicitly selected, other strategies will trigger the generation of TT.

**Comment by gschievelbein** [comment]
`generateTT` has a default value of `true` because so far we TT is required to create all models.

I would keep all those checks because if this requirement changes in the future, we still need to ensure that we have all dependencies.

**Comment by arrascue** [comment]
> I would keep all those checks because if this requirement changes in the future, we still need to ensure that we have all dependencies.

This is exactly the reason why I did it this way.

**Comment by polinankoleva** [comment]
To think what we can have in the future is nice, but to have multiple if/else checks that are always true only because of that do not make sense for me. I already made a pull request with the removal of generateTT. If you prefer these checks to stay, just close the pull request.

**Comment by gschievelbein** [comment]
If those conditions are not met, the program will crash. It makes sense that we handle that "gracefully". By removing those tests we reduce the code robustness.

**Comment by gschievelbein** [comment]
> It’s common for programmers to believe conditions can’t happen,
> and so not check for those conditions. Such conditions are most often
> merely highly unlikely. Indeed, even if the conditions cannot occur in the current
> version, repeated modifications and later additions to code may cause
> inconsistent effects, leading to these “impossible” cases happening. So the
> code needs to check for these conditions, and handle them appropriately
> (even if only by returning an error indicator).

Bishop, Matt, and Chip Elliott. "Robust programming by example." IFIP World Conference on Information Security Education. Springer, Berlin, Heidelberg, 2009.
