### ISSUE TITLE
When minimumGroupSize is equal 0

### ISSUE THREAD

**Issue by polinankoleva** [tf-dbis-uni-freiburg/PRoST#28]
Before introduction of IWPT and JWPT, there was a special option when minGroupSize was 0. I cannot find how to create a property table node with only one triple. Did you remove that?
https://github.com/tf-dbis-uni-freiburg/PRoST/blob/96643e002582b07acd3730d107a424c95c38f29a/query/PRoST-query/src/main/java/translator/Translator.java#L317

**Comment by gschievelbein** [comment]
Yes. I would suggest then that we have a new parameter, as this means that we are setting a **maximum** group size, not minimum.

**Comment by polinankoleva** [comment]
I am already working on the idea of adding a new parameter. But do not remove logical pieces of code like that without considering that someone might depend on that. If I haven't checked the code, I could have run experiments and report results without even knowing that something is not working correctly.

**Comment by polinankoleva** [comment]
This is fixed in pull request #31
