### ISSUE TITLE
Variable on predicate

### ISSUE THREAD

**Issue by matteuan** [tf-dbis-uni-freiburg/PRoST#4]
A triple pattern like " _subj ?p obj_ " generates an error.
It should be translated by using the tripletable instead.

**Comment by gschievelbein** [comment]
https://github.com/tf-dbis-uni-freiburg/PRoST/tree/wip/gs/graph_analysis

SQL query for a single pattern of type _subj ?p ?o_ is created using the wide property table.

TODO: Create that SQL query in a node. Deal with variable subjects (_?s_) and multiple patterns in a single node.

**Comment by gschievelbein** [comment]
Commit https://github.com/tf-dbis-uni-freiburg/PRoST/commit/9fb3525a1c526e81cff2a9c8bf6bc862a5abcbb5 fixed unreachable node types during the creation of the tree. TT nodes already support variable predicates.
