### ISSUE TITLE
correct findTableName

### ISSUE THREAD

**Issue by matteuan** [tf-dbis-uni-freiburg/PRoST#9]
Stats.findTableName() sometimes returns the wrong table name.

**Comment by arrascue** [comment]
I could not reproduce. Do you know when this could happen?

**Comment by matteuan** [comment]
It can happen when there are two properties with the same ending and some # in the middle. For example, "property1#name" and "property2#name". That function can confuse them. I did not find an example in the datasets we were using before, but this is not impossible, especially for DBpedia.

**Comment by polinankoleva** [comment]
I encountered this issue. For example, if we have predicates **<http://ogp.me/ns#description>** and **<http://www.w3.org/1999/xhtml/vocab#description>**. Then if you have a query like that 

```
SELECT  ?description
WHERE
  { <https://www.tehumardi.ee/peremaja-roosi-tiigi-kaldal/> <http://ogp.me/ns#description> ?description}
```

PRoST queries VP table **vp_http___www_w3_org_1999_xhtml_vocab_description** instead of **vp_http___ogp_me_ns_description**.

**Comment by polinankoleva** [comment]
@matteuan, this happens because the method does not only search for exact match but also accepts a match only in the ending or beginning. Can you give an example why do we need the latter? Isn't it better to accept only exact match?

**Comment by matteuan** [comment]
The prefix/suffix trick was added so we can have a combination of dataset with prefix and query without it, or viceversa. In practice, it's a buggy behavior because cases like the one you mentioned can happen.

**Comment by matteuan** [comment]
I would say a more definitive approach would be to enforce full URIs when loading. Additionally, it could be added the possibility of a loading with a prefixed dataset, if the user adds also a file with the prefix. Already in Sempala, there was a function for applying prefixes like this, you can see it [here](https://github.com/aschaetzle/Sempala/blob/master/sempala-loader/src/main/java/de/uni_freiburg/informatik/dbis/sempala/loader/Loader.java).

**Comment by polinankoleva** [comment]
Prefixes are not supported anymore. Full URI are stored. The table name is searched by an exact match.
